### PR TITLE
Add SciPy Internship experience

### PR DESCRIPTION
**Pull request by Smit-create**
- [x] The main subject relates to at least one project affiliated to the Scientific Python Ecosystem.
- [x] I have the right to publish the content under the BSD 3-Clause License for the code and Creative Common CC-BY-4.0 License for the text.

cc @rgommers

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks @Smit-create for writing this. I think it's a nice way to wrap up your internship work, and it's a good and pretty much complete overview of the many things you worked on.

I don't have more comments, since I already did detailed review on the draft in HackMD. The rendered version looks good.

I don't have merge rights on this repo, so I'll wait for someone else to push this over the finish line.

**Review by tupui — APPROVED** [review]
Thank you @Smit-create for the article and most importantly your work on SciPy 😃 and thanks @rgommers for the review.

CI is green and it renders good.

**Comment by tupui** [comment]
Ark I missed the format one (mobile UI had me confused). I will fix this later today

**Comment by tupui** [comment]
Fixed 😅

**Comment by rgommers** [comment]
Great, thanks @tupui. @Smit-create want to share a link to the post on the scipy-dev list?

**Comment by tupui** [comment]
I could share such things on our Twitter as well. What do you think?

**Comment by Smit-create** [comment]
Hi @rgommers and @tupui 
Yeah, I am okay with sharing this link. Should I share that or @tupui will share it?

**Pull request merged**
