### PR TITLE
Change: Condense and simplify all-posts page

### PR DESCRIPTION
**Pull request by alphapapa**
See <https://github.com/scientific-python/blog.scientific-python.org/issues/130>.

### CODE REVIEW

**Comment by alphapapa** [comment]
Will rebase this after https://github.com/scientific-python/blog.scientific-python.org/pull/144 is merged.

**Comment by jarrodmillman** [comment]
I am not sure #144 was needed, I already updated all the theme changes (other than the tag and changelog in #143). But I went ahead and merged it since it doesn't change anything. Once you rebase this on main, you should also set up your pre-commit hooks so the pre-commit bot is happy.

**Comment by alphapapa** [comment]
> I am not sure #144 was needed, I already updated all the theme changes (other than the tag and changelog in #143). But I went ahead and merged it since it doesn't change anything. Once you rebase this on main, you should also set up your pre-commit hooks so the pre-commit bot is happy.

Rebased and pushed.

Will try to take the pre-commit config into account in the future, but am having some trouble getting it running securely locally.

**Comment by jarrodmillman** [comment]
pre-commit.ci autofix

**Comment by stefanv** [comment]
This LGTM. It would be nice to have the "All posts..." texts a bit more prominent, and make it clear that it is a link. Did it not have an arrow before?

The all posts page looks good; double checking that there still is pagination in place?

**Comment by jarrodmillman** [comment]
This is what the `All posts ...` link looked like in early March:
2023-10-13T12:01:47,194619094-07:00

Here is what it looks like now:
2023-10-13T12:01:47,194619094-07:00

It looks to me nearly identical to what it was before. Since this PR was intended to be about the all-posts page, would it make sense to turn that into an issue and deal with it in its own PR?

I am hoping to make the PRs more focused, so they are easier to review and merge. We also have other things we want to work on and the longer these PRs remain unmerged the more difficult it is to deal with.

**Comment by jarrodmillman** [comment]
The remaining issue we were planning to deal with before merging this PR is removing the summaries from the actual posts page. I am marking this as a draft for now, so it isn't merged until that is addressed.

**Comment by alphapapa** [comment]
> Here is what it looks like now:

@jarrodmillman Oops, I think you used the wrong deploy-preview link for the "now" screenshot.  It doesn't look like that anymore.  See https://deploy-preview-137--blog-scientific-python-org.netlify.app/ for this PR's current appearance.

@stefanv I'll adjust the "All posts..." link to be more prominent.

Thanks.

**Comment by alphapapa** [comment]
Latest changes visible here: https://github.com/scientific-python/blog.scientific-python.org/issues/130#issuecomment-1763035014  Which includes changes made to the theme here: https://github.com/scientific-python/scientific-python-hugo-theme/pull/289

Marking as ready for review.

**Review by jarrodmillman — APPROVED** [review]

**Pull request merged**
