### PR TITLE
Add author link to numpy RNG post

### PR DESCRIPTION
**Pull request by albertcthomas**
Adding author info to Numpy RNG blog post following  https://github.com/scientific-python/scientific-python-hugo-theme/pull/503

Thanks!

### CODE REVIEW

**Comment by tupui** [comment]
Thanks @albertcthomas, we just need to wait a bit as the theme is not yet synchronised there. We are on v0.11 and we will wait for v0.12.

@jarrodmillman might be able to give a timeline (or as I suspect he might do, make it happen now 😅)

**Comment by albertcthomas** [comment]
Sure, no rush this is not urgent. I just did the PR now while it was on my mind :)

**Review by jarrodmillman — APPROVED** [review]

**Comment by albertcthomas** [comment]
Thanks a lot @jarrodmillman

**Comment by albertcthomas** [comment]
Yes this is perfect thanks. At some point if you need something that requires a bit less maintenance, just one page with all the authors and link to the url of their choice is also perfectly fine but the current solution is very nice!

**Pull request merged**
